//! Embedded Python runtime for the OpenCode Go backend.
//!
//! The Python 3.12 embeddable package (zip, ~12MB, includes requests) is
//! compiled into the exe via `include_bytes!`. On first use it is extracted
//! to `%LOCALAPPDATA%\advent-mcp-python` (marker file tracks the version),
//! then `python.exe` is spawned for requests that need a browser-like TLS
//! fingerprint (opencode.ai sits behind Cloudflare which blocks reqwest/curl
//! fingerprints but passes Python's urllib3/OpenSSL one).
//!
//! The zip is generated by `scripts/prepare_python_embed.ps1` and must exist
//! at build time (see that script for details). It is NOT committed to git.

use std::path::PathBuf;
use std::sync::Mutex;
use std::time::Instant;

/// Version marker — bump to force re-extraction after the embedded zip changes.
const PYTHON_EMBED_VERSION: &str = "20260806-1";

/// The embedded Python distribution (zip bytes).
const PYTHON_EMBED_ZIP: &[u8] = include_bytes!("../python-embed.zip");

/// Serialize extraction across concurrent MCP tool calls (Mutex, not async,
/// because extraction is short and blocking is acceptable).
static EXTRACT_LOCK: Mutex<()> = Mutex::new(());

fn local_app_data() -> Result<PathBuf, String> {
    std::env::var("LOCALAPPDATA")
        .map(PathBuf::from)
        .map_err(|_| "LOCALAPPDATA not set; cannot extract embedded Python".to_string())
}

/// Directory containing the extracted Python runtime (python.exe etc).
/// Extracts on first call (or when the marker version changes).
pub fn python_dir() -> Result<PathBuf, String> {
    let dest = local_app_data()?.join("advent-mcp-python");
    let marker = dest.join(".version");

    let need_extract = std::fs::read_to_string(&marker).map(|v| v != PYTHON_EMBED_VERSION).unwrap_or(true);
    if !need_extract && dest.join("python.exe").exists() {
        return Ok(dest);
    }

    // Serialize extraction.
    let _guard = EXTRACT_LOCK.lock().unwrap_or_else(|p| p.into_inner());

    // Re-check under lock (another thread may have extracted meanwhile).
    if std::fs::read_to_string(&marker).map(|v| v == PYTHON_EMBED_VERSION).unwrap_or(false)
        && dest.join("python.exe").exists() {
        return Ok(dest);
    }

    let t0 = Instant::now();
    eprintln!("🐍 Extracting embedded Python runtime to {} ...", dest.display());
    std::fs::create_dir_all(&dest).map_err(|e| format!("create {}: {}", dest.display(), e))?;

    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(PYTHON_EMBED_ZIP))
        .map_err(|e| format!("python-embed.zip corrupt: {}", e))?;
    for i in 0..archive.len() {
        let mut file = archive.by_index(i).map_err(|e| e.to_string())?;
        let out_path = dest.join(file.name());
        if file.is_dir() {
            std::fs::create_dir_all(&out_path).map_err(|e| e.to_string())?;
            continue;
        }
        if let Some(parent) = out_path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        let mut out = std::fs::File::create(&out_path).map_err(|e| e.to_string())?;
        std::io::copy(&mut file, &mut out).map_err(|e| e.to_string())?;
    }

    std::fs::write(&marker, PYTHON_EMBED_VERSION).map_err(|e| e.to_string())?;
    eprintln!("🐍 Python runtime ready in {:.1}s", t0.elapsed().as_secs_f32());
    Ok(dest)
}

/// Path to python.exe of the extracted runtime.
pub fn python_exe() -> Result<PathBuf, String> {
    Ok(python_dir()?.join("python.exe"))
}
