//! Embedded Python runtime for the OpenCode Go backend.
//!
//! **Windows**: the Python 3.12 embeddable package (zip, ~12MB, includes
//! requests) is compiled into the exe via `include_bytes!`. On first use it
//! is extracted to `%LOCALAPPDATA%\advent-mcp-python` (marker file tracks
//! the version), then `python.exe` is spawned for requests that need a
//! browser-like TLS fingerprint (opencode.ai sits behind Cloudflare which
//! blocks reqwest/curl fingerprints but passes Python's urllib3/OpenSSL one).
//! The zip is generated by `scripts/prepare_python_embed.ps1` and must exist
//! at build time (see that script for details). It is NOT committed to git.
//!
//! **Linux / macOS**: no embedded runtime; `python_exe()` returns the system
//! `python3` (verified to have `requests` installed) and the same script is
//! spawned with it.

use std::path::PathBuf;
#[cfg(target_os = "windows")]
use std::sync::Mutex;
#[cfg(target_os = "windows")]
use std::time::Instant;

/// Version marker — bump to force re-extraction after the embedded zip changes.
#[cfg(target_os = "windows")]
const PYTHON_EMBED_VERSION: &str = "20260806-1";

/// The embedded Python distribution (zip bytes). Windows-only: on other
/// platforms no zip is embedded, keeping the binary ~12MB smaller.
#[cfg(target_os = "windows")]
const PYTHON_EMBED_ZIP: &[u8] = include_bytes!("../python-embed.zip");

/// Serialize extraction across concurrent MCP tool calls (Mutex, not async,
/// because extraction is short and blocking is acceptable).
#[cfg(target_os = "windows")]
static EXTRACT_LOCK: Mutex<()> = Mutex::new(());

#[cfg(target_os = "windows")]
fn local_app_data() -> Result<PathBuf, String> {
    std::env::var("LOCALAPPDATA")
        .map(PathBuf::from)
        .map_err(|_| "LOCALAPPDATA not set; cannot extract embedded Python".to_string())
}

/// Directory containing the extracted Python runtime (python.exe etc).
/// Extracts on first call (or when the marker version changes).
/// Windows-only: the embedded zip is a Windows embeddable distribution;
/// on other platforms python_exe() never calls this.
#[cfg(target_os = "windows")]
pub fn python_dir() -> Result<PathBuf, String> {
    let dest = local_app_data()?.join("advent-mcp-python");
    let marker = dest.join(".version");

    let need_extract = std::fs::read_to_string(&marker).map(|v| v != PYTHON_EMBED_VERSION).unwrap_or(true);
    if !need_extract && dest.join("python.exe").exists() {
        return Ok(dest);
    }

    // Serialize extraction.
    let _guard = EXTRACT_LOCK.lock().unwrap_or_else(|p| p.into_inner());

    // Re-check under lock (another thread may have extracted meanwhile).
    if std::fs::read_to_string(&marker).map(|v| v == PYTHON_EMBED_VERSION).unwrap_or(false)
        && dest.join("python.exe").exists() {
        return Ok(dest);
    }

    let t0 = Instant::now();
    eprintln!("🐍 Extracting embedded Python runtime to {} ...", dest.display());
    std::fs::create_dir_all(&dest).map_err(|e| format!("create {}: {}", dest.display(), e))?;

    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(PYTHON_EMBED_ZIP))
        .map_err(|e| format!("python-embed.zip corrupt: {}", e))?;
    for i in 0..archive.len() {
        let mut file = archive.by_index(i).map_err(|e| e.to_string())?;
        let out_path = dest.join(file.name());
        if file.is_dir() {
            std::fs::create_dir_all(&out_path).map_err(|e| e.to_string())?;
            continue;
        }
        if let Some(parent) = out_path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        let mut out = std::fs::File::create(&out_path).map_err(|e| e.to_string())?;
        std::io::copy(&mut file, &mut out).map_err(|e| e.to_string())?;
    }

    std::fs::write(&marker, PYTHON_EMBED_VERSION).map_err(|e| e.to_string())?;
    eprintln!("🐍 Python runtime ready in {:.1}s", t0.elapsed().as_secs_f32());
    Ok(dest)
}

/// Path to python.exe of the extracted runtime (Windows).
#[cfg(target_os = "windows")]
pub fn python_exe() -> Result<PathBuf, String> {
    Ok(python_dir()?.join("python.exe"))
}

/// Path to a system Python 3 interpreter (Linux / macOS).
///
/// The go backend script uses `requests` (urllib3 TLS fingerprint passes
/// Cloudflare), so verify the interpreter and the library are usable and
/// return an actionable error message otherwise. Verified on every call —
/// the probe is ~tens of ms, negligible next to the ~90s API timeout.
#[cfg(not(target_os = "windows"))]
pub fn python_exe() -> Result<PathBuf, String> {
    use std::process::Command;

    let python = "python3";
    let probe = Command::new(python)
        .args(["-c", "import requests"])
        .output()
        .map_err(|e| format!("system '{}' not found or not executable: {}; install Python 3 (e.g. apt install python3 python3-requests)", python, e))?;
    if !probe.status.success() {
        let stderr = String::from_utf8_lossy(&probe.stderr);
        return Err(format!(
            "system '{}' cannot import requests: {}; install it (e.g. apt install python3-requests or pip install requests)",
            python, stderr.trim()
        ));
    }
    Ok(PathBuf::from(python))
}
